name: ameba
description: A static code analysis tool for Crystal
homepage: https://crystal-ameba.github.io/
licenses:
  - MIT
languages:
  - Crystal
categories:
  - Linter
source:
  id: pkg:github/crystal-ameba/ameba@v1.6.4
  build:
    run: make

bin:
  ameba: bin/ameba
