---
name: hyprls
description: A LSP server for Hyprland config files
homepage: https://github.com/hyprland-community/hyprls
licenses:
  - MIT
languages:
  - Hypr
categories:
  - LSP

source:
  id: pkg:golang/github.com/hyprland-community/hyprls@v0.2.0

bin:
  hyprls: golang:hyprls
