---
name: remark-language-server
description: A language server to lint and format markdown files with remark.
homepage: https://github.com/remarkjs/remark-language-server
licenses:
  - MIT
languages:
  - Markdown
categories:
  - LSP

source:
  id: pkg:npm/remark-language-server@3.0.0

schemas:
  lsp: vscode:https://raw.githubusercontent.com/remarkjs/vscode-remark/{{version}}/package.json

bin:
  remark-language-server: npm:remark-language-server
