---
name: htmx-lsp
description: An experimental LSP for HTMX.
homepage: https://github.com/ThePrimeagen/htmx-lsp
licenses:
  - MIT
languages:
  - HTMX
categories:
  - LSP

source:
  id: pkg:cargo/htmx-lsp@0.1.0

schemas:
  lsp: vscode:https://raw.githubusercontent.com/ThePrimeagen/htmx-lsp/{{version}}/client/vscode/package.json

bin:
  htmx-lsp: cargo:htmx-lsp
