---
name: drools-lsp
description: An implementation of a language server for the Drools Rule Language.
homepage: https://github.com/kiegroup/drools-lsp
licenses:
  - Apache-2.0
languages:
  - Drools
categories:
  - LSP

source:
  id: pkg:github/kiegroup/drools-lsp@latest
  asset:
    file: drools-lsp-server-jar-with-dependencies.jar

schemas:
  lsp: vscode:https://raw.githubusercontent.com/kiegroup/drools-lsp/{{version}}/client/package.json

share:
  drools-lsp/drools-lsp-server-jar-with-dependencies.jar: drools-lsp-server-jar-with-dependencies.jar
